name: Build and Deploy
on:
  push:
    branches: [ master ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1

      # install and build project
      - name: Install and Build 🔧
        run: |
          npm install
          npm run-script build

      # deploy to github-pages
      # see here: https://github.com/marketplace/actions/deploy-to-github-pages
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: page
          folder: .
